# Site settings
title: Coinprice
email: your-email@domain.com
description: >
  Documentation for AREA04's' Coinprice API.

baseurl: "/GHP-Coinprice" # the subpath of your site, e.g. /blog/
url: https://AREA04.github.io/GHP-Coinprice # the base hostname & protocol for your site
git_address: https://github.com/AREA04/GHP-Coinprice
git_edit_address: https://github.com/AREA04/GHP-Coinprice/blob/gh-pages

# Theme options from https://bootswatch.com/
# comment-out to use default Bootstrap
bootwatch: flatly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: US/Eastern
defaults:

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _about
    type: about
  values:
    layout: about
    sectionid: about

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  about:
    permalink: /:collection/:path/
    output: true

theme: jekyll-theme-midnight